### ISSUE TITLE
MyObject factories

### ISSUE THREAD

**Issue by hookmethods** [GuilhermeTrevizani/roleplay-server#2]
System.InvalidCastException: Unable to cast object of type 'AltV.Net.Elements.Entities.NetworkObject' to type 'Roleplay.Factories.MyObject'.
   at Roleplay.Entities.PropertyFurniture.CreateObject() in D:\roleplay-server\Roleplay\Entities\PropertyFurniture.cs:line 42
   at Roleplay.Server.OnStart() in D:\roleplay-server\Roleplay\Server.cs:line 223
   at Roleplay.Server.OnStart() in D:\roleplay-server\Roleplay\Server.cs:line 337
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by GuilhermeTrevizani** [comment]
Hello. Please don't use branch develop. I'm gonna try to reproduce it.
